name: Copy variables to new repo

on:
  repository_dispatch:
    types: [trigger-workflow]
  workflow_dispatch:

env:
  GIST_ID: dd2aa26e5b6c4152e80e7d3d09f2486a

jobs:
  copy-variables:
    runs-on: [self-hosted, linux]
    #runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Define and export environment variables
        env:
          REPO_NAME: ${{ github.event.repository.name }}
          GIST_ID: ${{ env.GIST_ID }}
        run: |
          gh variable set APPNAME --repo "${{ github.repository }}" --body "$REPO_NAME"
          gh variable set GISTID --repo "${{ github.repository }}" --body "$GIST_ID"
          gh variable set VERSION4D --repo "${{ github.repository }}" --body "20R10"

      - name: Update Version Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ env.GIST_ID }}
          filename: release_${{ github.event.repository.name }}.json
          label: Version
          message: 0.0.0
          color: blue

      - name: Update Download Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ env.GIST_ID }}
          filename: download_${{ github.event.repository.name }}.json
          label: Downloads
          message: 0
          color: green

      - name: Add the “4d” topic to the repo
        env:
          GH_TOKEN: ${{ secrets.TARGET_TOKEN_GITHUB }}
        run: |
          gh repo edit ${{ github.repository }} --add-topic 4d

      - name: Self destruction
        if: success()
        env:
          GH_TOKEN: ${{ secrets.TARGET_TOKEN_GITHUB }}
        run: |
          git clone --depth=1 https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} repo-cleanup
          cd repo-cleanup
      
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      
          rm .github/workflows/copy-vars.yml
          rm .github/workflows/create-repo.yml
          rm -r workflows
          rm README.md
      
          git add .
          git commit -m "Cleaning"
          git push origin main
